[
  {
    "LiveFrom": "01/01/2018",
    "CaseTypeID": "FINREM_ExceptionRecord",
    "ID": "createException",
    "Name": "Create an exception record",
    "Description": "Create an exception record",
    "DisplayOrder": 1,
    "PostConditionState": "ScannedRecordReceived",
    "SecurityClassification": "Public"
  },
  {
    "LiveFrom": "01/01/2018",
    "CaseTypeID": "FINREM_ExceptionRecord",
    "ID": "attachToExistingCase",
    "Name": "Attach record to existing case",
    "Description": "Attach record to existing case",
    "DisplayOrder": 2,
    "PreConditionState(s)": "ScannedRecordReceived",
    "PostConditionState": "ScannedRecordAttachedToCase",
    "CallBackURLAboutToSubmitEvent": "http://bulk-scan-orchestrator-aat.service.core-compute-aat.internal/callback/attach_case",
    "RetriesTimeoutURLAboutToSubmitEvent": 10,
    "SecurityClassification": "Public"
  },
  {
    "LiveFrom": "01/01/2018",
    "CaseTypeID": "FINREM_ExceptionRecord",
    "ID": "rejectRecord",
    "Name": "Reject record",
    "Description": "Reject record",
    "DisplayOrder": 4,
    "PreConditionState(s)": "ScannedRecordReceived",
    "PostConditionState": "ScannedRecordRejected",
    "SecurityClassification": "Public"
  },
  {
    "LiveFrom": "01/01/2018",
    "CaseTypeID": "FINREM_ExceptionRecord",
    "ID": "updateManually",
    "Name": "Manually handle record",
    "Description": "Manually handle record",
    "DisplayOrder": 5,
    "PreConditionState(s)": "ScannedRecordReceived",
    "PostConditionState": "ScannedRecordManuallyHandled",
    "SecurityClassification": "Public"
  }
]
